# Generated by Django 4.1.7 on 2023-04-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('journey_details', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('mode_details', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
